import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { app } from "@/db/db"
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth";

console.log(app)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isFirebaseInitialized, setIsFirebaseInitialized] = useState(false);
  const router = useRouter();
  const { user, role, loading } = useAuth();

  // List of routes to exclude from displaying the splash screen
  const excludedRoutes = ['/login', '/register'];

  if (!isFirebaseInitialized && !excludedRoutes.includes(router.pathname)) {
    return <div></div>
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
